version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      security-updates:
        applies-to: security-updates
        patterns: ["*"]
    open-pull-requests-limit: 5
